// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: set_pusher_request.proto

#ifndef PROTOBUF_set_5fpusher_5frequest_2eproto__INCLUDED
#define PROTOBUF_set_5fpusher_5frequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace set_pusher_request_msgs {
namespace msgs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_set_5fpusher_5frequest_2eproto();
void protobuf_AssignDesc_set_5fpusher_5frequest_2eproto();
void protobuf_ShutdownFile_set_5fpusher_5frequest_2eproto();

class SetPusherRequest;

// ===================================================================

class SetPusherRequest : public ::google::protobuf::Message {
 public:
  SetPusherRequest();
  virtual ~SetPusherRequest();
  
  SetPusherRequest(const SetPusherRequest& from);
  
  inline SetPusherRequest& operator=(const SetPusherRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SetPusherRequest& default_instance();
  
  void Swap(SetPusherRequest* other);
  
  // implements Message ----------------------------------------------
  
  SetPusherRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SetPusherRequest& from);
  void MergeFrom(const SetPusherRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string pusher = 1 [default = ""];
  inline bool has_pusher() const;
  inline void clear_pusher();
  static const int kPusherFieldNumber = 1;
  inline const ::std::string& pusher() const;
  inline void set_pusher(const ::std::string& value);
  inline void set_pusher(const char* value);
  inline void set_pusher(const char* value, size_t size);
  inline ::std::string* mutable_pusher();
  inline ::std::string* release_pusher();
  
  // @@protoc_insertion_point(class_scope:set_pusher_request_msgs.msgs.SetPusherRequest)
 private:
  inline void set_has_pusher();
  inline void clear_has_pusher();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* pusher_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_set_5fpusher_5frequest_2eproto();
  friend void protobuf_AssignDesc_set_5fpusher_5frequest_2eproto();
  friend void protobuf_ShutdownFile_set_5fpusher_5frequest_2eproto();
  
  void InitAsDefaultInstance();
  static SetPusherRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// SetPusherRequest

// required string pusher = 1 [default = ""];
inline bool SetPusherRequest::has_pusher() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SetPusherRequest::set_has_pusher() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SetPusherRequest::clear_has_pusher() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SetPusherRequest::clear_pusher() {
  if (pusher_ != &::google::protobuf::internal::kEmptyString) {
    pusher_->clear();
  }
  clear_has_pusher();
}
inline const ::std::string& SetPusherRequest::pusher() const {
  return *pusher_;
}
inline void SetPusherRequest::set_pusher(const ::std::string& value) {
  set_has_pusher();
  if (pusher_ == &::google::protobuf::internal::kEmptyString) {
    pusher_ = new ::std::string;
  }
  pusher_->assign(value);
}
inline void SetPusherRequest::set_pusher(const char* value) {
  set_has_pusher();
  if (pusher_ == &::google::protobuf::internal::kEmptyString) {
    pusher_ = new ::std::string;
  }
  pusher_->assign(value);
}
inline void SetPusherRequest::set_pusher(const char* value, size_t size) {
  set_has_pusher();
  if (pusher_ == &::google::protobuf::internal::kEmptyString) {
    pusher_ = new ::std::string;
  }
  pusher_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SetPusherRequest::mutable_pusher() {
  set_has_pusher();
  if (pusher_ == &::google::protobuf::internal::kEmptyString) {
    pusher_ = new ::std::string;
  }
  return pusher_;
}
inline ::std::string* SetPusherRequest::release_pusher() {
  clear_has_pusher();
  if (pusher_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = pusher_;
    pusher_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace set_pusher_request_msgs

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_set_5fpusher_5frequest_2eproto__INCLUDED
